version: '3.8'

services:
  db:
    image: postgres:15
    container_name: secureguard_db
    environment:
      POSTGRES_USER: secureguard
      POSTGRES_PASSWORD: secureguard123
      POSTGRES_DB: secureguard_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: